image: node:latest

stages:
  - trigger
  - setup
  - build
  - package
  - release

.yarn_job_template:
  tags:
    - gitlab-org
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash

trigger:
  stage: trigger
  tags:
    - gitlab-org
  only:
    refs:
      - master
  allow_failure: false
  script:
    - echo Starting pipeline

install-dependencies:
  extends: .yarn_job_template
  stage: setup
  script:
    - yarn install --cache-folder .yarn
  cache:
    key: 'yarn-server-cache_$CI_PROJECT_ID'
    paths:
      - .yarn
    policy: pull-push
  artifacts:
    expire_in: 1 week
    paths:
      - 'node_modules/'
      - 'packages/*/node_modules/'

build-apps:
  extends: .yarn_job_template
  dependencies:
    - install-dependencies
  stage: build
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - 'build/'
      - 'packages/*/build/'
      - 'packages/*/dist/'

package:
  extends: .yarn_job_template
  dependencies:
    - install-dependencies
    - build-apps
  stage: package
  script:
    - ./package.sh
  artifacts:
    expire_in: 1 week
    paths:
      - 'futbot.zip'
release:
  stage: release
  tags:
    - gitlab-org
  dependencies:
    - install-dependencies
    - package
  script:
    - yarn semantic-release
